# Experiment artefacts
# Cat2Vec
CAT2VEC_MODEL = "cat2vec.model"
CAT2VEC_ENCODING_IMG = "cat2vec_embedding.png"
# Seq2Seq
SEQ2SEQ_CONFIG_NAME = "seq2seq_config.yaml"
SEQ2SEQ_MODEL = "seq2seq.model"
SEQ2SEQ_LOSS_PLOT = "seq2seq_loss.png"
SEQ2SEQ_BATLOW_LOSS_PLOT = "seq2seq_barlow_loss.png"
SEQ2SEQ_ENCODING_IMG = "seq2seq_embedding_on_encodings.png"
SEQ2SEQ_DECODING_IMG = "seq2seq_embedding_on_decodings.png"
SEQ2SEQ_CLUSTERING_IMG = "seq2seq_embedded_clusters.png"
FINAL_REPRESENTATIONS = "final_representations.npz"
# Defrag
DEFRAG_CONFIG_NAME = "defrag_config.yaml"
CLUSTERS_CSV = "clustered_events.csv"
CLUSTERS_STATS = "clustered_stats.yaml"
NXG_PLOT = "networkX_graph.png"
GTG_PLOT = "graph_tool_graph.png"
GTG_PLOT_ALPHA = "graph_tool_graph_alpha.png"
GTG_PLOT_PDF = "graph_tool_graph.pdf"
GTG_SOFT_PLOT = "graph_tool_graph_soft.png"
GTG_SOFT_PLOT_ALPHA = "graph_tool_graph_soft_alpha.png"
GTG_SOFT_PLOT_PDF = "graph_tool_graph_soft.pdf"
SOFT_ADJACENCY_MATRIX = "soft_adjacency_matrix.png"
DEFRAG_RESULTS = "defrag_results.yaml"
DEFRAG_DATA = "defrag_data.npz"
